[packages.apt]
    to_remove = ["btop", "htop", "dnsutils"]
    [packages.apt.common]
        packages = [
            "bat",                 # cat with syntax highlighting and Git integration
            "curl",
            "fzf",
            "git",
            "git-extras",
            "gnupg",
            "gpg",
            "jq",
            "nano",
            "tmux",
            "unzip",
            "wget",
        ]